name: Rust Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-nix-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ github.workflow }}-${{ hashFiles('flake.lock', '**/*.nix', 'Cargo.lock', '**/Cargo.toml') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ github.workflow }}-
          gc-max-store-size-linux: 4G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-${{ github.workflow }}-
          purge-created: 0
          purge-last-accessed: P7D
          purge-primary-key: never

      - name: Check formatting
        run: nix build .#checks.x86_64-linux.rust-fmt -L

      - name: Run clippy
        run: nix build .#checks.x86_64-linux.clippy -L

      - name: Run Rust tests
        run: nix build .#checks.x86_64-linux.rust-tests -L

      - name: Build docs
        run: nix build .#checks.x86_64-linux.cargo-doc -L
